version: "3"
services:
  app:
    container_name: app
    image: node_app
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/nodejs-app
      - ./src/node_modules/:/var/www/nodejs-app/src/node_modules
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /Users/paliz/Desktop/dbdata:/data/db
    ports:
      - '27018:27017'
    command: mongod